Resources:
    CodePipelineRole:
        Type: AWS::IAM::Role
        Properties:
            
            AssumeRolePolicyDocument:
                Statement:
                - Action: ['sts:AssumeRole']
                  Effect: Allow
                  Principal:
                    Service: [codepipeline.amazonaws.com]
                Version: '2012-10-17'
            Path: /
            Policies:
                - PolicyName: CodePipelineAccess
                  PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                    - Effect: Allow
                      Resource: 'arn:aws:s3:::*/*' 
                      Action:
                        - 's3:*'
                    - Effect: Allow
                      Resource: '*' 
                      Action:
                        - 'codebuild:*'
                        - 'codedeploy:*'